export default {
    email_placeholder :"Email",
    password_placeholder:"mot de passe",
    login_button:"connexion",
    register_link:"S'enregistrer",
    forgot_password_link:"mot de passe oublie?",
    facebook_login_button:'connectez-vous avec Facebook.',
    password_blank_messege:'le mot de passe ne peut pas etre vide',
    password_alphaNumeric_check:'Le mot de passe doit comporter au moins 1 caractère alphanumérique et une longueur comprise entre 8 et 15.',
    password_complexity_check:'Le mot de passe doit contenir au moins 1 lettre minuscule, 1 lettre majuscule, 1 chiffre, 1 caractère spécial et une longueur de 6 à 10',
    valid_email_check:'mettez une adresse mail valide.',
    facebook_login_error:'Vous avez déjà un compte avec cette adresse e-mail. Veuillez vous connecter avec votre email et votre mot de passe.',
    forgot_password_success_messege:'Un lien de réinitialisation du mot de passe envoyé à votre adresse e-mail, veuillez vérifier et réinitialiser votre nouveau mot de passe.',
    facebook_login_auth_error:'Erreur de connexion Facebook :',
    static_notification_title:'Notification MTC',
    refferal_code_validation_modal:'Validation de votre code de parrainage...',
    refferal_id_not_match_error:'identifiant de parrainage invalide',
    registration_title:'Inscription',
    first_name_placeholder:'Prénom',
    first_name_blank_error:"Entrez votre prénom s'il vous plait.",
    last_name_placeholder:'Nom de famille',
    last_name_blank_error:'Veuillez entrer votre nom de famille.',
    mobile_no_placeholder:'Numéro de telephone',
    mobile_no_blank_error:'Veuillez entrer un numéro de telephone valide.',
    confrim_password_placeholder:'Confirmer le mot de passe',
    confrim_password_not_match_err:'Le mot de passe ne correspond pas',
    referral_id_placeholder:'Identifiant de parrainage (facultatif)',
    register_button:'Sinscrire maintenant',
    email_exist_error:'adresse e-mail déjà utilisée par un autre compte.',
    Account_linking_error:'Erreur lors association de compte',
    send_email_button:'Envoyer un e-mail',
    book_your_ride_menu:'Réservez votre trajet',
    profile_setting_menu:'Paramètres de profil',
    my_wallet_menu:'Mon portefeuille',
    my_rides_menu:'Mes trajets',
    about_us_menu:'À propos de nous',
    logout:'Se déconnecter',
    photo_upload_action_sheet_title:'Choisissez un type de média ?',
    camera:'Appareil photo',
    galery:'Galerie',
    cancel:'Annuler',
    yes:'Yes',
    network_request_failed:'Network request failed',
    password_update_messege:'You Password successfully updated',
    delete_account_modal_title:'Confrmation',
    delete_account_modal_subtitle:'Do you want to delete your account ?',
    profile_page_title:'My Profile',
    my_wallet_title:'My Wallet Balance',
    profile_page_subtitle:'Profile Details',
    location_lebel:'Location',
    language_lebel:'Language',
    preffer_language:'English',
    change_password_lebel:'Change Password',
    delete_account_lebel:'Delete Account',
    change_password_modal_title:'Change Password?',
    old_password_placeholder:'Old Password',
    new_password_placeholder:'New Password',
    old_password_validation_error:'Please enter a old password',
    new_password_validation_error:'Please enter a new password',
    update_button:'Update Now',
    update_profile_title:'Upadate Profile',
    map_screen_where_input_text:'Where From ?',
    map_screen_drop_input_text:'Drop Where ?',
    driver_finding_alert:'Finding Drivers for you',
    no_driver_found_alert_title:'Alert!',
    no_driver_found_alert_messege:'Sorry, No Drivers found right now.Please try again later',
    no_driver_found_alert_OK_button:'OK',
    no_driver_found_alert_TRY_AGAIN_button:'Try Again',
    pickup_and_drop_location_blank_error:'Select pickup and drop location',
    pickup_location_blank_error:'Select pickup location',
    drop_location_blank_error:'Select drop location',
    car_type_blank_error:'Select car type',
    congratulation:'Congratulations!',
    refferal_bonus_messege_text:'Your referral bonus ammount -',
    map_screen_title:'Grab My Taxi',
    cab_selection_title:'Pick Your Travel Cab',
    cab_selection_subtitle:'Tap to select car type and book now',
    not_available:'Not Available',
    book_now_button:'Book Now',
    contact_details:'Contact Details',
    phone:'Phone',
    my_wallet_tile:'My Wallet',
    wallet_ballance:'Wallet Balance',
    add_money:'Add Money',
    transaction_history_title:'Wallet Transaction History',
    successfully:'Successfully',
    form_wallet:'form wallet',
    Transaction_Id :'Transaction Id ',
    ride_list_title:'My Rides',
    no_car_assign_text:'No car assign',
    not_found_text:'Not Found',
    ride_details_page_title:'My Rides Details',
    you_rated_text:'You Rated',
    car_no_not_found:'Car Number Not found',
    track_now_button:'Track Now',
    bill_details_title:'Bill Details',
    your_trip:'Your Trip',
    discount:'Discount',
    promo_apply:'(Promo Apply)',
    grand_total:'Grand Total',
    payment_status:'Payment Status',
    paynow_button:'Pay Now',
    call_driver:'Call Driver',
    booked_cab_title:'Booked Cab',
    you_selected:'You Selected -',
    otp:'OTP :',
    driver_assign_messege:'Driver will Assign Soon..',
    cancel_ride:'Cancel Ride',
    rider_cancel_text:'Ride Cancel',
    cancel_messege1:'Your ride with Booking Id',
    cancel_messege2:'has been cancelled successfully',
    dont_cancel_text:'Don\'t Cancel',
    cancel_reason_modal_title:'What\'s Cancel Reason',
    chat_title:'Chat',
    send_button_text:'Send',
    chat_input_title:'Type something nice...',
    chat_not_found:'No chat history found',
    card_payment_blank_error:'Please fill up all the details properly.',
    payment_amound_error:'Payment amount is too small.',
    invalid_card_details_error:'Card is not valid.',
    success_payment:'Payment Successfull',
    confrimation:'Confrimation',
    payment_alert:'Do you want to delete your card ?',
    please_wait:'Please wait...',
    enterCVV:'Please Enter Your CVV',
    your_promo:'Your promo',
    promo_exp:'Sorry!\nPromo code and Promo usage limit has expired.',
    promo_limit:'Sorry!\nPromo usage limit over.',
    promo_eligiblity:'SORRY!\nyou are not eligible for this promo.',
    payment:'Payment',
    bill_details:'Bill Details',
    apply_promo:'Apply Promo',
    your_fare:'Your Fare',
    promo_discount:'Promo Discount',
    wallet_discount:'Wallet Discount',
    payable_ammount:'Payable Ammount',
    use_wallet_balance:'Use Wallet Cash (Your balance - ',
    pay_cash:'Pay with cash',
    pay_card:'Pay with Card',
    proceed_pay:'Proceed to Pay',
    save_card:'Your Saved Cards',
    thanks:'Thanks For Rating',
    skip:'Skip',
    receipt:'Receipt',
    rate_ride:'PLEASE RATE YOUR RIDE',
    err:'Error!',
    route_not_found:'Cannot found any route',
    sorry:'Sorry',
    multipleBooking:'MTC currently doesn\'t support multiple bookings.',
    driver_not_found:'We cannot assign driver at this moment. contact to adminstrator !!',
    new_booking_request_push_notification:'You Have A New Booking Request',
    fare_details:'Fare Details',
    base_fare:'Base Fare',
    convenience_free:'Convenience Fees',
    total_fare:'Total Fare',
    inclusive_tax:'(Inclusive all Taxes)',
    nb:'N.B.: Your fare will be increased if toll, route and destination changes or if ride took longer due to traffic orother',
    confrim_booking:'Confirm Booking',
    estimate_fare_text:'This is your Estimate fare only',
    done:'Done',
    notification_headerText:'Notification',
    notification_not_found:'No notification found',
    track_cab:'Track Your Cab',
    location_permission:'Location Access Permission',
    ask_me_later:'Ask Me Later',
    min_order_value:'Minimum order value-',
    add_money_tile:'Add Money',
    addMoneyTextInputPlaceholder:'Add Amount (FC)',
    transactionFaildMsg:'Transaction Failed',
    payWithCard:'Pay With Card',
    CardPaymentAmount:'Pay by card',
    CashPaymentAmount:'Pay by cash',
    WalletPayment:'Pay by wallet',
    pay_mode:'Payment Mode',
    Balance:'GrabCab Balance',
    android_channel: 'GrabCab Notifications'
}
